shared: &shared
  steps:
    # NOTE: there is a problem with Circle's Debian image and libcups2 needs to be removed so we can install ghostscript
    - run: sudo apt-get update && sudo apt-get purge -y libcups2 && sudo apt-get install -y ghostscript
    - checkout
    - restore_cache:
        keys:
          - gems-{{ checksum "Gemfile.lock" }}
    - restore_cache:
        keys:
          - yarn-{{ checksum "yarn.lock" }}
    - run: 'sed -i "s/#gem ''pg''/gem ''pg''/" Gemfile'
    - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - run: yarn install
    - save_cache:
        key: gems-{{ checksum "Gemfile.lock" }}
        paths:
          - ./vendor/bundle
    - save_cache:
        key: yarn-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
    - run:
        name: Wait for db
        command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 1m
    - run: cp config/$DB_CONFIG_FILENAME config/database.yml
    - run: cp config/secrets.yml.example config/secrets.yml
    - run: bundle exec rake db:create db:schema:load
    - run: bundle exec rails webpacker:compile
    - run:
        name: rspec
        command: |
          bundle exec rspec --profile 10 \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

version: 2
jobs:
  mysql:
    docker:
      - image: circleci/ruby:2.3-node-browsers
        environment:
          - RAILS_ENV=test
          - DB_HOST=127.0.0.1
          - DB_PORT=3306
          - DB_CONFIG_FILENAME=database.ci.mysql.yml
      - image: circleci/mysql:5.6
    working_directory: ~/repo
    <<: *shared
  postgres:
    docker:
      - image: circleci/ruby:2.3-node-browsers
        environment:
          - RAILS_ENV=test
          - DB_HOST=127.0.0.1
          - DB_PORT=5432
          - DB_CONFIG_FILENAME=database.ci.postgres.yml
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=onebody
        - POSTGRES_DB=onebody_test
    working_directory: ~/repo
    <<: *shared
workflows:
  version: 2
  build:
    jobs:
      - mysql
      - postgres
