af-ZA: "Afrikaans (Suid-Afrika)"
cs: "Česky"
da: "Dansk"
de: "Deutsch"
en: "English"
es-419: "Español (Latinoamérica)"
de: "Deutsch"
fr: "Français"
nl-NL: "Nederlands (Nederland)"
pt-BR: "Português (Brasil)"
ro: "Română"
ru: "Русский"
zh-CN: "简体中文"
