all:
    inject_view: true
    stack_trace_lines: 3
    trace_includes_vendor: false
    trace_includes_lib: true
    profiling: enabled
    production_data: true
    max_safe_key_length: 100
    disable_sql_cache: true    

    warn_severity: 3
    critical_severity: 7

    warn_select_count: 20
    critical_select_count: 50

    warn_update_count: 5
    critical_update_count: 10

    warn_insert_count: 5
    critical_insert_count: 10

    warn_delete_count: 5
    critical_delete_count: 10

    warn_duration_threshold: 0.2
    critical_duration_threshold: 1.0

    warn_affected_rows: 10
    critical_affected_rows: 100

development:
    enabled: true

production:
    enabled: false

test:
    enabled: false